<?php
/**
 * CaseResolutionStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;
use \Kloutit\ObjectSerializer;

/**
 * CaseResolutionStatus Class Doc Comment
 *
 * @category Class
 * @description New status of the case. &#x60;&#x60;ALLEGED&#x60;&#x60;: you have sent the generated defense to the payment processor yourself (only from &#x60;&#x60;GENERATED&#x60;&#x60;). &#x60;&#x60;ACCEPTED&#x60;&#x60;: you accept the chargeback and stop defending the case (from &#x60;&#x60;PENDING&#x60;&#x60;, &#x60;&#x60;GENERATED&#x60;&#x60;, &#x60;&#x60;ALLEGED&#x60;&#x60;, &#x60;&#x60;REOPENED&#x60;&#x60;, &#x60;&#x60;PREARBITRATION&#x60;&#x60; or &#x60;&#x60;ARBITRATION&#x60;&#x60;). &#x60;&#x60;WON&#x60;&#x60; / &#x60;&#x60;LOST&#x60;&#x60;: outcome of the case once its defense has been sent (only from &#x60;&#x60;ALLEGED&#x60;&#x60;). A resolved case cannot change its status again.
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CaseResolutionStatus
{
    /**
     * Possible values of this enum
     */
    public const ALLEGED = 'ALLEGED';

    public const WON = 'WON';

    public const LOST = 'LOST';

    public const ACCEPTED = 'ACCEPTED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ALLEGED,
            self::WON,
            self::LOST,
            self::ACCEPTED
        ];
    }
}


