<?php
/**
 * CaseStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;
use \Kloutit\ObjectSerializer;

/**
 * CaseStatus Class Doc Comment
 *
 * @category Class
 * @description Current status of the case.
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CaseStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'PENDING';

    public const GENERATING = 'GENERATING';

    public const GENERATED = 'GENERATED';

    public const ALLEGING = 'ALLEGING';

    public const ALLEGED = 'ALLEGED';

    public const WON = 'WON';

    public const LOST = 'LOST';

    public const ACCEPTED = 'ACCEPTED';

    public const EXPIRED = 'EXPIRED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::GENERATING,
            self::GENERATED,
            self::ALLEGING,
            self::ALLEGED,
            self::WON,
            self::LOST,
            self::ACCEPTED,
            self::EXPIRED
        ];
    }
}


