<?php
/**
 * CaseSector
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;
use \Kloutit\ObjectSerializer;

/**
 * CaseSector Class Doc Comment
 *
 * @category Class
 * @description Sector of the case. It must be one of the sectors of the organization, for instance: EDUCATION, SOFTWARE, TRAVEL_HOTEL,...
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CaseSector
{
    /**
     * Possible values of this enum
     */
    public const DIGITAL_PRODUCT = 'DIGITAL_PRODUCT';

    public const EDUCATION = 'EDUCATION';

    public const FASHION = 'FASHION';

    public const FOOD = 'FOOD';

    public const GAMING = 'GAMING';

    public const HEALTH_BEAUTY = 'HEALTH_BEAUTY';

    public const HOME = 'HOME';

    public const LEISURE = 'LEISURE';

    public const MARKETPLACE = 'MARKETPLACE';

    public const PARKING = 'PARKING';

    public const PHONE = 'PHONE';

    public const SOFTWARE = 'SOFTWARE';

    public const SPORT = 'SPORT';

    public const SUBSCRIPTION = 'SUBSCRIPTION';

    public const SUPPLY = 'SUPPLY';

    public const TECHNOLOGY = 'TECHNOLOGY';

    public const TRANSPORT = 'TRANSPORT';

    public const TRAVEL_AIRLINE = 'TRAVEL_AIRLINE';

    public const TRAVEL_HOTEL = 'TRAVEL_HOTEL';

    public const RENTING_VEHICLE = 'RENTING_VEHICLE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DIGITAL_PRODUCT,
            self::EDUCATION,
            self::FASHION,
            self::FOOD,
            self::GAMING,
            self::HEALTH_BEAUTY,
            self::HOME,
            self::LEISURE,
            self::MARKETPLACE,
            self::PARKING,
            self::PHONE,
            self::SOFTWARE,
            self::SPORT,
            self::SUBSCRIPTION,
            self::SUPPLY,
            self::TECHNOLOGY,
            self::TRANSPORT,
            self::TRAVEL_AIRLINE,
            self::TRAVEL_HOTEL,
            self::RENTING_VEHICLE
        ];
    }
}


