<?php
/**
 * ChargebackReason
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;
use \Kloutit\ObjectSerializer;

/**
 * ChargebackReason Class Doc Comment
 *
 * @category Class
 * @description Reason why the customer is requesting the chargeback.
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChargebackReason
{
    /**
     * Possible values of this enum
     */
    public const FRAUD = 'FRAUD';

    public const PRODUCT_SERVICE_NOT_RECEIVED = 'PRODUCT_SERVICE_NOT_RECEIVED';

    public const DEFECTIVE_PRODUCT_SERVICE = 'DEFECTIVE_PRODUCT_SERVICE';

    public const PRODUCT_SERVICE_NOT_AS_DESCRIBED = 'PRODUCT_SERVICE_NOT_AS_DESCRIBED';

    public const INCORRECT_DUPLICATED_CHARGES = 'INCORRECT_DUPLICATED_CHARGES';

    public const PRODUCT_SERVICE_CANCELLED = 'PRODUCT_SERVICE_CANCELLED';

    public const REFUND_NOT_RECEIVED = 'REFUND_NOT_RECEIVED';

    public const RECURRENT_OPERATION_CANCELLED = 'RECURRENT_OPERATION_CANCELLED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FRAUD,
            self::PRODUCT_SERVICE_NOT_RECEIVED,
            self::DEFECTIVE_PRODUCT_SERVICE,
            self::PRODUCT_SERVICE_NOT_AS_DESCRIBED,
            self::INCORRECT_DUPLICATED_CHARGES,
            self::PRODUCT_SERVICE_CANCELLED,
            self::REFUND_NOT_RECEIVED,
            self::RECURRENT_OPERATION_CANCELLED
        ];
    }
}


