<?php
/**
 * ClientWebhookEventDetailsDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;

use \ArrayAccess;
use \Kloutit\ObjectSerializer;

/**
 * ClientWebhookEventDetailsDto Class Doc Comment
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClientWebhookEventDetailsDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ClientWebhookEventDetailsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sector' => 'string',
        'chargeback_reason' => 'string',
        'deadline' => '\DateTime',
        'order_number' => 'string',
        'transaction_id' => 'string',
        'transaction_date' => '\DateTime',
        'bank_name' => 'string',
        'card_brand' => 'string',
        'last4_digits' => 'string',
        'is3_ds_purchase' => 'bool',
        'dispute_amount' => '\Kloutit\Model\WebhookEventAmountDto',
        'purchase_date' => '\DateTime',
        'purchase_amount' => '\Kloutit\Model\WebhookEventAmountDto',
        'is_charge_refundable' => 'bool',
        'customer_name' => 'string',
        'customer_email' => 'string',
        'customer_phone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sector' => null,
        'chargeback_reason' => null,
        'deadline' => 'date-time',
        'order_number' => null,
        'transaction_id' => null,
        'transaction_date' => 'date-time',
        'bank_name' => null,
        'card_brand' => null,
        'last4_digits' => null,
        'is3_ds_purchase' => null,
        'dispute_amount' => null,
        'purchase_date' => 'date-time',
        'purchase_amount' => null,
        'is_charge_refundable' => null,
        'customer_name' => null,
        'customer_email' => null,
        'customer_phone' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sector' => false,
        'chargeback_reason' => false,
        'deadline' => false,
        'order_number' => false,
        'transaction_id' => false,
        'transaction_date' => false,
        'bank_name' => false,
        'card_brand' => false,
        'last4_digits' => false,
        'is3_ds_purchase' => false,
        'dispute_amount' => false,
        'purchase_date' => false,
        'purchase_amount' => false,
        'is_charge_refundable' => false,
        'customer_name' => false,
        'customer_email' => false,
        'customer_phone' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sector' => 'sector',
        'chargeback_reason' => 'chargebackReason',
        'deadline' => 'deadline',
        'order_number' => 'orderNumber',
        'transaction_id' => 'transactionId',
        'transaction_date' => 'transactionDate',
        'bank_name' => 'bankName',
        'card_brand' => 'cardBrand',
        'last4_digits' => 'last4Digits',
        'is3_ds_purchase' => 'is3DSPurchase',
        'dispute_amount' => 'disputeAmount',
        'purchase_date' => 'purchaseDate',
        'purchase_amount' => 'purchaseAmount',
        'is_charge_refundable' => 'isChargeRefundable',
        'customer_name' => 'customerName',
        'customer_email' => 'customerEmail',
        'customer_phone' => 'customerPhone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sector' => 'setSector',
        'chargeback_reason' => 'setChargebackReason',
        'deadline' => 'setDeadline',
        'order_number' => 'setOrderNumber',
        'transaction_id' => 'setTransactionId',
        'transaction_date' => 'setTransactionDate',
        'bank_name' => 'setBankName',
        'card_brand' => 'setCardBrand',
        'last4_digits' => 'setLast4Digits',
        'is3_ds_purchase' => 'setIs3DsPurchase',
        'dispute_amount' => 'setDisputeAmount',
        'purchase_date' => 'setPurchaseDate',
        'purchase_amount' => 'setPurchaseAmount',
        'is_charge_refundable' => 'setIsChargeRefundable',
        'customer_name' => 'setCustomerName',
        'customer_email' => 'setCustomerEmail',
        'customer_phone' => 'setCustomerPhone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sector' => 'getSector',
        'chargeback_reason' => 'getChargebackReason',
        'deadline' => 'getDeadline',
        'order_number' => 'getOrderNumber',
        'transaction_id' => 'getTransactionId',
        'transaction_date' => 'getTransactionDate',
        'bank_name' => 'getBankName',
        'card_brand' => 'getCardBrand',
        'last4_digits' => 'getLast4Digits',
        'is3_ds_purchase' => 'getIs3DsPurchase',
        'dispute_amount' => 'getDisputeAmount',
        'purchase_date' => 'getPurchaseDate',
        'purchase_amount' => 'getPurchaseAmount',
        'is_charge_refundable' => 'getIsChargeRefundable',
        'customer_name' => 'getCustomerName',
        'customer_email' => 'getCustomerEmail',
        'customer_phone' => 'getCustomerPhone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('sector', $data ?? [], null);
        $this->setIfExists('chargeback_reason', $data ?? [], null);
        $this->setIfExists('deadline', $data ?? [], null);
        $this->setIfExists('order_number', $data ?? [], null);
        $this->setIfExists('transaction_id', $data ?? [], null);
        $this->setIfExists('transaction_date', $data ?? [], null);
        $this->setIfExists('bank_name', $data ?? [], null);
        $this->setIfExists('card_brand', $data ?? [], null);
        $this->setIfExists('last4_digits', $data ?? [], null);
        $this->setIfExists('is3_ds_purchase', $data ?? [], null);
        $this->setIfExists('dispute_amount', $data ?? [], null);
        $this->setIfExists('purchase_date', $data ?? [], null);
        $this->setIfExists('purchase_amount', $data ?? [], null);
        $this->setIfExists('is_charge_refundable', $data ?? [], null);
        $this->setIfExists('customer_name', $data ?? [], null);
        $this->setIfExists('customer_email', $data ?? [], null);
        $this->setIfExists('customer_phone', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sector
     *
     * @return string|null
     */
    public function getSector()
    {
        return $this->container['sector'];
    }

    /**
     * Sets sector
     *
     * @param string|null $sector Case sector
     *
     * @return self
     */
    public function setSector($sector)
    {
        if (is_null($sector)) {
            throw new \InvalidArgumentException('non-nullable sector cannot be null');
        }
        $this->container['sector'] = $sector;

        return $this;
    }

    /**
     * Gets chargeback_reason
     *
     * @return string|null
     */
    public function getChargebackReason()
    {
        return $this->container['chargeback_reason'];
    }

    /**
     * Sets chargeback_reason
     *
     * @param string|null $chargeback_reason Chargeback reason reported by the payment processor
     *
     * @return self
     */
    public function setChargebackReason($chargeback_reason)
    {
        if (is_null($chargeback_reason)) {
            throw new \InvalidArgumentException('non-nullable chargeback_reason cannot be null');
        }
        $this->container['chargeback_reason'] = $chargeback_reason;

        return $this;
    }

    /**
     * Gets deadline
     *
     * @return \DateTime|null
     */
    public function getDeadline()
    {
        return $this->container['deadline'];
    }

    /**
     * Sets deadline
     *
     * @param \DateTime|null $deadline Deadline to submit the dispute response
     *
     * @return self
     */
    public function setDeadline($deadline)
    {
        if (is_null($deadline)) {
            throw new \InvalidArgumentException('non-nullable deadline cannot be null');
        }
        $this->container['deadline'] = $deadline;

        return $this;
    }

    /**
     * Gets order_number
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     *
     * @param string|null $order_number Merchant's order number, when the payment processor reports it
     *
     * @return self
     */
    public function setOrderNumber($order_number)
    {
        if (is_null($order_number)) {
            throw new \InvalidArgumentException('non-nullable order_number cannot be null');
        }
        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets transaction_id
     *
     * @return string|null
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param string|null $transaction_id PSP transaction id
     *
     * @return self
     */
    public function setTransactionId($transaction_id)
    {
        if (is_null($transaction_id)) {
            throw new \InvalidArgumentException('non-nullable transaction_id cannot be null');
        }
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets transaction_date
     *
     * @return \DateTime|null
     */
    public function getTransactionDate()
    {
        return $this->container['transaction_date'];
    }

    /**
     * Sets transaction_date
     *
     * @param \DateTime|null $transaction_date transaction_date
     *
     * @return self
     */
    public function setTransactionDate($transaction_date)
    {
        if (is_null($transaction_date)) {
            throw new \InvalidArgumentException('non-nullable transaction_date cannot be null');
        }
        $this->container['transaction_date'] = $transaction_date;

        return $this;
    }

    /**
     * Gets bank_name
     *
     * @return string|null
     */
    public function getBankName()
    {
        return $this->container['bank_name'];
    }

    /**
     * Sets bank_name
     *
     * @param string|null $bank_name bank_name
     *
     * @return self
     */
    public function setBankName($bank_name)
    {
        if (is_null($bank_name)) {
            throw new \InvalidArgumentException('non-nullable bank_name cannot be null');
        }
        $this->container['bank_name'] = $bank_name;

        return $this;
    }

    /**
     * Gets card_brand
     *
     * @return string|null
     */
    public function getCardBrand()
    {
        return $this->container['card_brand'];
    }

    /**
     * Sets card_brand
     *
     * @param string|null $card_brand card_brand
     *
     * @return self
     */
    public function setCardBrand($card_brand)
    {
        if (is_null($card_brand)) {
            throw new \InvalidArgumentException('non-nullable card_brand cannot be null');
        }
        $this->container['card_brand'] = $card_brand;

        return $this;
    }

    /**
     * Gets last4_digits
     *
     * @return string|null
     */
    public function getLast4Digits()
    {
        return $this->container['last4_digits'];
    }

    /**
     * Sets last4_digits
     *
     * @param string|null $last4_digits last4_digits
     *
     * @return self
     */
    public function setLast4Digits($last4_digits)
    {
        if (is_null($last4_digits)) {
            throw new \InvalidArgumentException('non-nullable last4_digits cannot be null');
        }
        $this->container['last4_digits'] = $last4_digits;

        return $this;
    }

    /**
     * Gets is3_ds_purchase
     *
     * @return bool|null
     */
    public function getIs3DsPurchase()
    {
        return $this->container['is3_ds_purchase'];
    }

    /**
     * Sets is3_ds_purchase
     *
     * @param bool|null $is3_ds_purchase is3_ds_purchase
     *
     * @return self
     */
    public function setIs3DsPurchase($is3_ds_purchase)
    {
        if (is_null($is3_ds_purchase)) {
            throw new \InvalidArgumentException('non-nullable is3_ds_purchase cannot be null');
        }
        $this->container['is3_ds_purchase'] = $is3_ds_purchase;

        return $this;
    }

    /**
     * Gets dispute_amount
     *
     * @return \Kloutit\Model\WebhookEventAmountDto|null
     */
    public function getDisputeAmount()
    {
        return $this->container['dispute_amount'];
    }

    /**
     * Sets dispute_amount
     *
     * @param \Kloutit\Model\WebhookEventAmountDto|null $dispute_amount dispute_amount
     *
     * @return self
     */
    public function setDisputeAmount($dispute_amount)
    {
        if (is_null($dispute_amount)) {
            throw new \InvalidArgumentException('non-nullable dispute_amount cannot be null');
        }
        $this->container['dispute_amount'] = $dispute_amount;

        return $this;
    }

    /**
     * Gets purchase_date
     *
     * @return \DateTime|null
     */
    public function getPurchaseDate()
    {
        return $this->container['purchase_date'];
    }

    /**
     * Sets purchase_date
     *
     * @param \DateTime|null $purchase_date purchase_date
     *
     * @return self
     */
    public function setPurchaseDate($purchase_date)
    {
        if (is_null($purchase_date)) {
            throw new \InvalidArgumentException('non-nullable purchase_date cannot be null');
        }
        $this->container['purchase_date'] = $purchase_date;

        return $this;
    }

    /**
     * Gets purchase_amount
     *
     * @return \Kloutit\Model\WebhookEventAmountDto|null
     */
    public function getPurchaseAmount()
    {
        return $this->container['purchase_amount'];
    }

    /**
     * Sets purchase_amount
     *
     * @param \Kloutit\Model\WebhookEventAmountDto|null $purchase_amount purchase_amount
     *
     * @return self
     */
    public function setPurchaseAmount($purchase_amount)
    {
        if (is_null($purchase_amount)) {
            throw new \InvalidArgumentException('non-nullable purchase_amount cannot be null');
        }
        $this->container['purchase_amount'] = $purchase_amount;

        return $this;
    }

    /**
     * Gets is_charge_refundable
     *
     * @return bool|null
     */
    public function getIsChargeRefundable()
    {
        return $this->container['is_charge_refundable'];
    }

    /**
     * Sets is_charge_refundable
     *
     * @param bool|null $is_charge_refundable is_charge_refundable
     *
     * @return self
     */
    public function setIsChargeRefundable($is_charge_refundable)
    {
        if (is_null($is_charge_refundable)) {
            throw new \InvalidArgumentException('non-nullable is_charge_refundable cannot be null');
        }
        $this->container['is_charge_refundable'] = $is_charge_refundable;

        return $this;
    }

    /**
     * Gets customer_name
     *
     * @return string|null
     */
    public function getCustomerName()
    {
        return $this->container['customer_name'];
    }

    /**
     * Sets customer_name
     *
     * @param string|null $customer_name customer_name
     *
     * @return self
     */
    public function setCustomerName($customer_name)
    {
        if (is_null($customer_name)) {
            throw new \InvalidArgumentException('non-nullable customer_name cannot be null');
        }
        $this->container['customer_name'] = $customer_name;

        return $this;
    }

    /**
     * Gets customer_email
     *
     * @return string|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customer_email'];
    }

    /**
     * Sets customer_email
     *
     * @param string|null $customer_email customer_email
     *
     * @return self
     */
    public function setCustomerEmail($customer_email)
    {
        if (is_null($customer_email)) {
            throw new \InvalidArgumentException('non-nullable customer_email cannot be null');
        }
        $this->container['customer_email'] = $customer_email;

        return $this;
    }

    /**
     * Gets customer_phone
     *
     * @return string|null
     */
    public function getCustomerPhone()
    {
        return $this->container['customer_phone'];
    }

    /**
     * Sets customer_phone
     *
     * @param string|null $customer_phone customer_phone
     *
     * @return self
     */
    public function setCustomerPhone($customer_phone)
    {
        if (is_null($customer_phone)) {
            throw new \InvalidArgumentException('non-nullable customer_phone cannot be null');
        }
        $this->container['customer_phone'] = $customer_phone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


