<?php
/**
 * Currencies
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;
use \Kloutit\ObjectSerializer;

/**
 * Currencies Class Doc Comment
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Currencies
{
    /**
     * Possible values of this enum
     */
    public const EUR = 'EUR';

    public const GBP = 'GBP';

    public const CHF = 'CHF';

    public const NOK = 'NOK';

    public const DKK = 'DKK';

    public const SEK = 'SEK';

    public const BGN = 'BGN';

    public const HRK = 'HRK';

    public const CZK = 'CZK';

    public const HUF = 'HUF';

    public const PLN = 'PLN';

    public const RON = 'RON';

    public const ISK = 'ISK';

    public const RUB = 'RUB';

    public const MKD = 'MKD';

    public const RSD = 'RSD';

    public const ARS = 'ARS';

    public const BOB = 'BOB';

    public const BRL = 'BRL';

    public const CLP = 'CLP';

    public const COP = 'COP';

    public const CRC = 'CRC';

    public const CUP = 'CUP';

    public const DOP = 'DOP';

    public const GTQ = 'GTQ';

    public const HNL = 'HNL';

    public const MXN = 'MXN';

    public const NIO = 'NIO';

    public const PAB = 'PAB';

    public const PYG = 'PYG';

    public const PEN = 'PEN';

    public const SRD = 'SRD';

    public const UYU = 'UYU';

    public const VES = 'VES';

    public const USD = 'USD';

    public const CAD = 'CAD';

    public const CNY = 'CNY';

    public const JPY = 'JPY';

    public const INR = 'INR';

    public const KRW = 'KRW';

    public const IDR = 'IDR';

    public const MYR = 'MYR';

    public const PHP = 'PHP';

    public const SGD = 'SGD';

    public const THB = 'THB';

    public const VND = 'VND';

    public const HKD = 'HKD';

    public const TWD = 'TWD';

    public const _TRY = 'TRY';

    public const AUD = 'AUD';

    public const NZD = 'NZD';

    public const FJD = 'FJD';

    public const PGK = 'PGK';

    public const WST = 'WST';

    public const VUV = 'VUV';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EUR,
            self::GBP,
            self::CHF,
            self::NOK,
            self::DKK,
            self::SEK,
            self::BGN,
            self::HRK,
            self::CZK,
            self::HUF,
            self::PLN,
            self::RON,
            self::ISK,
            self::RUB,
            self::MKD,
            self::RSD,
            self::ARS,
            self::BOB,
            self::BRL,
            self::CLP,
            self::COP,
            self::CRC,
            self::CUP,
            self::DOP,
            self::GTQ,
            self::HNL,
            self::MXN,
            self::NIO,
            self::PAB,
            self::PYG,
            self::PEN,
            self::SRD,
            self::UYU,
            self::VES,
            self::USD,
            self::CAD,
            self::CNY,
            self::JPY,
            self::INR,
            self::KRW,
            self::IDR,
            self::MYR,
            self::PHP,
            self::SGD,
            self::THB,
            self::VND,
            self::HKD,
            self::TWD,
            self::_TRY,
            self::AUD,
            self::NZD,
            self::FJD,
            self::PGK,
            self::WST,
            self::VUV
        ];
    }
}


