<?php
/**
 * FileCategoryEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;
use \Kloutit\ObjectSerializer;

/**
 * FileCategoryEnum Class Doc Comment
 *
 * @category Class
 * @description Category of the file
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FileCategoryEnum
{
    /**
     * Possible values of this enum
     */
    public const RECEIPT = 'RECEIPT';

    public const CUSTOMER_COMMUNICATION = 'CUSTOMER_COMMUNICATION';

    public const CUSTOMER_SIGNATURE = 'CUSTOMER_SIGNATURE';

    public const PAYMENT_AUTHORIZATION = 'PAYMENT_AUTHORIZATION';

    public const BUYER_IDENTITY_PROOF = 'BUYER_IDENTITY_PROOF';

    public const PRODUCT_EVIDENCE_BEFORE_DURING_PURCHASE = 'PRODUCT_EVIDENCE_BEFORE_DURING_PURCHASE';

    public const CANCELLATION_REQUEST = 'CANCELLATION_REQUEST';

    public const REFUND_PROOF = 'REFUND_PROOF';

    public const TERMS_AND_CONDITIONS_ACCEPTED_PROOF = 'TERMS_AND_CONDITIONS_ACCEPTED_PROOF';

    public const DUPLICATE_PAYMENT_RECORDS = 'DUPLICATE_PAYMENT_RECORDS';

    public const DEVICE_DATA_AND_IP_ADDRESSES = 'DEVICE_DATA_AND_IP_ADDRESSES';

    public const PRODUCT_IMAGE = 'PRODUCT_IMAGE';

    public const ORDER_HISTORY_AND_TRANSACTIONS = 'ORDER_HISTORY_AND_TRANSACTIONS';

    public const USAGE_PROOF = 'USAGE_PROOF';

    public const SHIPPING_AND_DELIVERY_CONFIRMATION = 'SHIPPING_AND_DELIVERY_CONFIRMATION';

    public const RECURRING_CONSENT_PROOF = 'RECURRING_CONSENT_PROOF';

    public const CUSTOMER_UNCATEGORIZED_FILE = 'CUSTOMER_UNCATEGORIZED_FILE';

    public const COMPANY_UNCATEGORIZED_FILE = 'COMPANY_UNCATEGORIZED_FILE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RECEIPT,
            self::CUSTOMER_COMMUNICATION,
            self::CUSTOMER_SIGNATURE,
            self::PAYMENT_AUTHORIZATION,
            self::BUYER_IDENTITY_PROOF,
            self::PRODUCT_EVIDENCE_BEFORE_DURING_PURCHASE,
            self::CANCELLATION_REQUEST,
            self::REFUND_PROOF,
            self::TERMS_AND_CONDITIONS_ACCEPTED_PROOF,
            self::DUPLICATE_PAYMENT_RECORDS,
            self::DEVICE_DATA_AND_IP_ADDRESSES,
            self::PRODUCT_IMAGE,
            self::ORDER_HISTORY_AND_TRANSACTIONS,
            self::USAGE_PROOF,
            self::SHIPPING_AND_DELIVERY_CONFIRMATION,
            self::RECURRING_CONSENT_PROOF,
            self::CUSTOMER_UNCATEGORIZED_FILE,
            self::COMPANY_UNCATEGORIZED_FILE
        ];
    }
}


