<?php
/**
 * FileCategoryEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2024 Kloutit Technologies S.L.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kloutit\Model;
use \Kloutit\ObjectSerializer;

/**
 * FileCategoryEnum Class Doc Comment
 *
 * @category Class
 * @description Category of the file
 * @package  Kloutit
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FileCategoryEnum
{
    /**
     * Possible values of this enum
     */
    public const RECEIPT = 'RECEIPT';

    public const CUSTOMER_COMMUNICATION = 'CUSTOMER_COMMUNICATION';

    public const CUSTOMER_SIGNATURE = 'CUSTOMER_SIGNATURE';

    public const PAYMENT_AUTHORIZATION = 'PAYMENT_AUTHORIZATION';

    public const CUSTOMER_VISUAL_EVIDENCE = 'CUSTOMER_VISUAL_EVIDENCE';

    public const CUSTOMER_UNCATEGORIZED_FILE = 'CUSTOMER_UNCATEGORIZED_FILE';

    public const PRODUCT_IMAGE = 'PRODUCT_IMAGE';

    public const CANCELLATION_POLICY = 'CANCELLATION_POLICY';

    public const REFUND_POLICY = 'REFUND_POLICY';

    public const REFUND_EVIDENCE = 'REFUND_EVIDENCE';

    public const TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS';

    public const DUPLICATE_CHARGE_DOCUMENTATION = 'DUPLICATE_CHARGE_DOCUMENTATION';

    public const SERVICE_EVIDENCE = 'SERVICE_EVIDENCE';

    public const SHIPPING_EVIDENCE = 'SHIPPING_EVIDENCE';

    public const COMPANY_VISUAL_EVIDENCE = 'COMPANY_VISUAL_EVIDENCE';

    public const COMPANY_UNCATEGORIZED_FILE = 'COMPANY_UNCATEGORIZED_FILE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RECEIPT,
            self::CUSTOMER_COMMUNICATION,
            self::CUSTOMER_SIGNATURE,
            self::PAYMENT_AUTHORIZATION,
            self::CUSTOMER_VISUAL_EVIDENCE,
            self::CUSTOMER_UNCATEGORIZED_FILE,
            self::PRODUCT_IMAGE,
            self::CANCELLATION_POLICY,
            self::REFUND_POLICY,
            self::REFUND_EVIDENCE,
            self::TERMS_AND_CONDITIONS,
            self::DUPLICATE_CHARGE_DOCUMENTATION,
            self::SERVICE_EVIDENCE,
            self::SHIPPING_EVIDENCE,
            self::COMPANY_VISUAL_EVIDENCE,
            self::COMPANY_UNCATEGORIZED_FILE
        ];
    }
}


